### ISSUE TITLE
General points to fix

### ISSUE THREAD

**Issue by LinaYahya** [GSG-G11/Fitness-house#144]
- [x] give price at single gym profile more font-weight
- [x] check if no reviews exist to not render the reviews section at all.
- [x] Don't render rate component at gym card if rate zero.
- [x] Don't render rate component at profile page rate zero.
- [x] fix 

https://github.com/GSG-G11/Fitness-house/blob/3b77a66fa506b7174a8b0ca356ce1035b872f17f/client/src/Components/SearchPage/CardResultFilter/Card.jsx#L19-L22
to 
```js
      <div className="image__card">
        {images.length && <img alt="complex" src={images[0].pathUrl} />}
      </div>
``` 
at `Components/SearchPage/CardResultFilter/Card.jsx`

- [x] fix selector at `singleGym` modal from `useSelector` to get data from `useGetGymDataQuery`
- [x] fix ⬇️  at `Components/HomePage/OfferForYou/index.jsx` as it redirect to `/gyms` which is not found
https://github.com/GSG-G11/Fitness-house/blob/3b77a66fa506b7174a8b0ca356ce1035b872f17f/client/src/Components/HomePage/OfferForYou/index.jsx#L92

**Comment by AhmedQeshta** [comment]
# On Filter Page :

## Bug 1 👍🏻  In Filter inputtake a static data form `client\src\Services`
 `client\src\Components\SearchPage\FilterSide\index.jsx` 
```jsx
    // ...
   import gymData from "./gymdata";
   // ...
```
`client\src\Services`
```js
const gymData = {
  cities: ["غزة", "خانيونس", "رفح"],
  //...
  }
```

##  Bug 2 👍🏻 loading Component width is not good

![image](https://user-images.githubusercontent.com/38624002/170238076-ac9d68fc-932a-45ab-a3ac-c908c63dc7f7.png)

## Component width like this:
![image](https://user-images.githubusercontent.com/38624002/170241045-ebddf765-76fe-459f-9a67-b5b99dce8da9.png)

**Comment by AFahgan** [comment]
Fix Slider when user make the price 0

**Comment by AFahgan** [comment]
Replace "احجز الآن" in the home page to "اعرض المزيد"
